server:
    port: 3000

spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:<Port>/<Database name>
        username: <Username>
        password: <Password>
    
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://sso.example.com/realms/exampleRealm
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

            client:
                registration:
                    ssodat:
                        clientId: <Example client>